apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: appdemo
  namespace: appdemo
  
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-app-demo-app-demo
  serviceName: app-demo
  template:
    metadata: 
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-app-demo-app-demo
    spec:
      containers:
      - image: 10195/app-demo:6
        name: app-demo
        ports:
        - containerPort: 8080
          protocol: TCP
      spec:
  controller:
    env:
    - name: ARGOCD_RECONCILIATION_TIMEOUT
      value: 0s
